### PR TITLE
feat(init): added flag for dir to install editor

### PR DESCRIPTION
**Pull request by realmike33**
broken install due to no pages dir(expected since I have my files in src)
Screen Shot 2020-09-09 at 11 27 05 AM
fixed install due to using new flag
Screen Shot 2020-09-09 at 11 27 13 AM
output
Screen Shot 2020-09-09 at 11 27 22 AM

### CODE REVIEW

**Comment by traversng** [comment]
@realmike33 I don't see a pages directory in src. I believe it needs to be `src/pages` or if `src/pages` exists then it needs to go in the existing pages dir.

[https://nextjs.org/docs/advanced-features/src-directory](https://nextjs.org/docs/advanced-features/src-directory)

**Comment by realmike33** [comment]
> @realmike33 I don't see a pages directory in src. I believe it needs to be `src/pages` or if `src/pages` exists then it needs to go in the existing pages dir.
> 
> https://nextjs.org/docs/advanced-features/src-directory

yeah the flag isnt for pages or src/pages. the flag is so you can put any dir of your choice

**Comment by traversng** [comment]
@realmike33 
If the current DX is we install on pages if it exists otherwise you need to pass a flag and path, it could be improved by:

1. try to find pages on the root to install
2. try to find src/pages on root
3. error and print the flag help command

because 99% of our users will fall into 1 and 2, we shouldn't ask them to pass a flag for them, but we do have the flag for the 1%

**Comment by Hendrixer** [comment]
putting our pages in any dir of there choice would basically break tipe. Next.js only supports `/pages` and `/src/pages`. So for the **BEST** exp:

1. look for `/pages`
2. look for `/src/pages`
3. install our pages in whichever one you find
4. if they have both then prompt them to resolve (all prompts will have flag options in the future, in product board already)
5. if they have neither than create `/pages`

For a good enough one:
don't do 4 or 5 and don't install our pages

**Comment by realmike33** [comment]
Screen Shot 2020-09-09 at 11 27 22 AM

**Review by Hendrixer — APPROVED** [review]

**Pull request merged**
